var version = ('1.0.0')
alert('Welcome to Top of Decent Calculator v'+version)
var altititude_airport = Number(prompt('What is the altititude of the arrival airport(ft)?','ex. 83'))
var altititude_cruise = Number(prompt('What is your cruising altititude (ft)?','ex. 32000'))
var minutes = Number((Math.floor((altititude_cruise-(3000+altititude_airport))/2500))+2)
var altititude_msl = Number(3000+altititude_airport)
var altititude_msl_round = Number((Math.ceil((3000+altititude_airport)/100))*100)
var minutes_slow = Number(minutes-5)
alert('TOD is at '+minutes+' minutes until arrival\n          Set altititude to '+altititude_msl+'ft ('+altititude_msl_round+'ft)\n          Set VS to -2500ft/min\nAt '+minutes_slow+' minutes until arrival\n          Set speed to 180kts\n          Turn on flight spoliers\nWhen you see the airport\n          Set VS to -800ft/min\n                    Go +100 each minute until you get to '+altititude_msl+'ft ('+altititude_msl_round+'ft), use Zulu time\nAt 7 minutes to arrival\n          Set spoliers to armed\nWhen glideslope indicator is in the middle\n          Take over plane or autoland')
